import 'package:hive/hive.dart';

part 'upload_task.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 0)
class UploadTask extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String filePath;

  @HiveField(2)
  final String teamId;

  @HiveField(3)
  final String sessionId;

  @HiveField(4)
  final bool isExcuse;

  @HiveField(5)
  final String? message;

  @HiveField(6)
  final DateTime createdAt;

  UploadTask({
    required this.id,
    required this.filePath,
    required this.teamId,
    required this.sessionId,
    required this.isExcuse,
    this.message,
    required this.createdAt,
  });
}
